### ISSUE TITLE
Constraints declared in the recipe do not correspond to constraints found in index.json of main conda channel.

### ISSUE THREAD

**Issue by rs2** [conda-forge/pyjwt-feedstock#20]
### Conda package in question
https://anaconda.org/main/pyjwt/2.1.0/download/win-64/pyjwt-2.1.0-py36haa95532_0.tar.bz2

### Issue
`meta.yaml` inside the said tarball declares `cryptography >=2.6,<3.0.0`
`index.json` in conda main channel declares `cryptography >=3.3.1,<4.0.0`
```bash
$ conda search pyjwt=2.1.0=py39haa95532_0 --info
Loading channels: done
pyjwt 2.1.0 py39haa95532_0
--------------------------
file name   : pyjwt-2.1.0-py39haa95532_0.conda
name        : pyjwt
version     : 2.1.0
build       : py39haa95532_0
build number: 0
size        : 32 KB
license     : MIT
subdir      : win-64
url         : https://repo.anaconda.com/pkgs/main/win-64/pyjwt-2.1.0-py39haa95532_0.conda
md5         : e754d2b9054fbc45bb0260c17af3d626
timestamp   : 2021-04-29 07:52:48 UTC
constraints :
  - cryptography >=3.3.1,<4.0.0
dependencies:
  - python >=3.9,<3.10.0a0
```

**Comment by tpdownes** [comment]
The contemporary constraints in the upstream repo had the upper-bound removed on October 18, 2021:

https://github.com/jpadilla/pyjwt/commit/19ce9c5ec7947428d35aaffd302eb2629210a697#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52

The impact of this here is that now we are stuck not upgrading either `pyjwt` or `cryptography`.

```shell
~❯❯❯ conda update --name default --all --yes
Collecting package metadata (current_repodata.json): done
Solving environment: |
Warning: 2 possible package resolutions (only showing differing packages):
  - conda-forge/noarch::pyjwt-2.3.0-pyhd8ed1ab_0, conda-forge/osx-64::cryptography-35.0.0-py39h209aa08_2
  - conda-forge/noarch::pyjwt-1.7.1-py_0, conda-forge/osx-64::cryptography-36.0.0-py39h209aa08done
```

I believe that it makes sense to remove the upper bound here, too.
